### ISSUE TITLE
Question - is it possible that the returned Future from a write is completed successfully before the actual write happens?

### ISSUE THREAD

**Issue by flozano** [spotify/folsom#65]
I have a cache abstraction layer in my project. This abstraction layer was implemented with xmemcached and now I'm porting it to use folsom. As part of it, I have tests that check the functionality:

``` java
    @Test
    public void setAsyncExpiration() throws Exception {
        Person p = aPerson();
        assertTrue(cache().setAsync(regionKey1, p, 2, TimeUnit.SECONDS).get());
        Thread.sleep(2100);
        assertNull(cache().get(regionKey1, Person.class));
    }
```

cache() returns the instance of my abstracted client, which in case of folsom implements the setAsync operation as:

``` java
    @Override
    protected CompletableFuture<Boolean> setAsync(String key, Object value, long expiration, TimeUnit timeUnit) {
        return toCompletableFuture(client.set(key, value, (int) timeUnit.toSeconds(expiration)))
                .thenApply(MemcacheStatus.OK::equals).exceptionally(x -> false);
    }
```

This test, however, randomly fails with Folsom: the assertNull fails saying that an instance of the object was returned instead of null (note that expiration is 2 seconds and, after the get() over the returned future, a sleep of 2.1 seconds happens).

**Comment by spkrka** [comment]
Thanks for the report.

The asynchronous set operation is supposed to return a future that completes once the memcache service responds.

To troubleshoot this further it would help to have more information:
1) Can you share a branch or repo with a minimal test case to reproduce this?
2) What kind of memcache service are you using to talk to? Is it possible that the problem is there?

Some preliminary guessing follows:
Perhaps the folsom code or the memcache service is rounding up/down the time in full seconds when setting the expiration, so it would pass or fail depending on when the test runs. I would personally change the sleep to 3000 milliseconds instead to make it more reliable.

**Comment by spkrka** [comment]
Closing this since there hasn't been any updates. Please reopen if there's any new data

**Comment by flozano** [comment]
I am afraid I missed this notification and never answered 🤦 

As a reference, current versions of folsom don't reproduce the issue. The memcached service was just the then-current version memcached (hosted by AWS elasticache)

Thanks anyway and sorry again for missing the answer.
