### ISSUE TITLE
Yammer metrics to Dropwizard?

### ISSUE THREAD

**Issue by Addvilz** [spotify/folsom#66]
This lib has a dependency on Yammer metrics, which, as far as I know, are now Dropwizard metrics. Any chance this might get migrated?

**Comment by mattnworb** [comment]
Should be pretty trivial to rewrite https://github.com/spotify/folsom/blob/master/src/main/java/com/spotify/folsom/client/YammerMetrics.java or create an implementation that uses the updated package/class names, as I think all the functionality is identical. With that said, since the metrics implementation is up to you as a user to use or supply, you could already use another package (like the dropwizard-branded metrics lib) already today without changes to folsom.

**Comment by Addvilz** [comment]
@mattnworb another might-be-an-issue is that metrics is not an optional dependency. Somewhat pollutes the dependencies then.

**Comment by Addvilz** [comment]
We encountered couple of more issues with dependencies (for example, we use Guava 21), so we forked and fixed things around.

https://github.com/mobilecashout/folsom/commit/8c533002434a881cf5de7e6d49609556d0927c5c

If this looks like something you are willing to have, I can branch out and prepare a proper PR, but for now, we had to hurry :)
