### ISSUE TITLE
Client lifetime, usage in Vert.x app

### ISSUE THREAD

**Issue by manikantag** [spotify/folsom#90]
Hi,

I've few questions about the usage:

1. _Quoting from README:_

    > Clients are single use, after shutdown has been invoked the client can no longer be used.

    Can't we create a long lived client, like Memcached suggest? I mean, is is ok if I create client once and use it throughout the app lifetime? What does '**Clients are single use**' means?

2. I want to use this client in vert.x based app and as this project also uses Netty, I thought this is a perfect fit. Have you aware of any issues while using with vert.x?

3. Can I assume the project will be maintained further?

4. Is it possible to merge the pending PRs?

Thanks.

**Comment by danielnorberg** [comment]
Single use here means that if you call `shutdown()` on a client you cannot use that instance any further, you have to create a new one.

It is fine to create a single client and use it throughout your app lifetime. Just don't call `shutdown()`.

I don't have any experience using this with vert.x, but apart from figuring out the dependencies I guess it should just work.

We have a lot of internal projects using folsom so I think we'll be maintaining it for some time to come.

**Comment by manikantag** [comment]
Thanks for the confirmation @danielnorberg 

> We have a lot of internal projects using folsom so I think we'll be maintaining it for some time to come.

I hope the '_some time to come_' will be enough time for us to switch to different cache when needed. Also, I assume this library is mature enough as Spotify is using it a lot as you mentioned. Just out of curiosity, can I assume the stability is in similar lines of spymemcached lib?

**Comment by spkrka** [comment]
Regarding the pending PR's, I just closed one of them that was most likely not needed due to other fixes instead.
#57 is probably too old and out of sync with master to merge (perhaps it's even fixed in another way, I don't remember)
#26 is definitely too old to merge - it should be remade with latest master if we want it.

We have not measured or compared stability with spymemcached, but we've successfully used folsom in production systems for a long time now with high load and not noticed any issues. I don't know what the current state of spymemcached is, but the reason we started working on folsom to begin with was that we noticed that spymemcached futures sometimes would get stuck and never complete.

It will likely be maintained at least for as long as we use it internally, but even if we stop maintaining it it should be reasonably easy for someone to take over or fork it. According to `cloc` the source code is less than 4000 lines of Java so it would hopefully not be overly complex.

**Comment by manikantag** [comment]
@spkrka Make sense. Thanks for the clarifications.
